services:
  mysql:
    container_name: mysql-DB
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: globalcc
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ssafy
      TZ: 'Asia/Seoul'
    ports:
      -  "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/ubuntu/docker/mysqlData:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - www
  redis:
    container_name: redis
    image: redis
    networks:
      - www
  rabbitMQ:
    container_name: rabbitmq
    image: a501/rabbitmq
    expose:
      - 5672
      - 15672
      - 61613
    restart: unless-stopped
    networks:
      - www
  application:
    container_name: spring-server
    restart: unless-stopped
    image:
      a501/backend
    env_file: "spring.env"
    environment:
      - DEEPL_API=${DEEPL_API}
      - JWT_SECRET=${JWT_SECRET}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    volumes:
      - ./resources/:/app/resources
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
      - rabbitMQ
    networks:
      - www
networks:
  www:
    name: www
    driver: bridge
